# yaml-language-server: $schema=https://json.schemastore.org/prettierrc
# https://prettier.io/docs/configuration
printWidth: 120
trailingComma: all
overrides:
  - files: "*.md"
    options:
      proseWrap: always
