# https://docs.astral.sh/ruff/configuration/
line-length = 100
target-version = "py313"
cache-dir = ".cache/ruff"

exclude = [".cache", ".venv", "__pycache__"]
include = ["src/**/*.py", "tests/**/*.py", "pyproject.toml"]

[format]
  docstring-code-format = true
  docstring-code-line-length = "dynamic"
