exclude = [
  ".venv/**",
  "node_modules/**",
  ".cache/**",
  ".pytest_cache/**",
  ".ruff_cache/**",
  ".serena/**",
]
include = ["**/*.toml"]

[formatting]
  align_comments = true
  array_auto_collapse = false
  column_width = 120
  indent_entries = true
  reorder_arrays = false
  reorder_inline_tables = true
  reorder_keys = true
